# Generated by Django 3.1.3 on 2020-12-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201213_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Client Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tlf',
            field=models.CharField(max_length=10, verbose_name='Phone number'),
        ),
    ]
